<?php
session_start();
if (!isset($_SESSION['username'])) {
    header("Location: flipkart_str_php.php");
    exit();
}

$host = 'localhost';
$db   = 'evanik_main';
$user = 'root';
$pass = 'evanik@2019';

try {
    $pdo = new PDO("mysql:host=$host;dbname=$db", $user, $pass);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch (PDOException $e) {
    die("DB Connection Failed: " . $e->getMessage());
}

$message = "";
$is_admin = 0; // Initialize is_admin variable

// Check if user is admin from flipkart_str_users
try {
    $stmt = $pdo->prepare("SELECT is_admin FROM flipkart_str_users WHERE id = ?");
    $stmt->execute([$_SESSION['user_id']]);
    $is_admin = (int)$stmt->fetchColumn();
} catch (PDOException $e) {
    // If any error, default to non-admin
    $is_admin = 0;
}

// If redirected back with message
if (!empty($_GET['msg'])) {
    $message = $_GET['msg'];
}

if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    // We'll support only the "generate" action from dashboard to generate report_id
    $action = isset($_POST['action']) ? $_POST['action'] : 'generate';

    if ($action === 'generate') {
        $flipkart_user_id = $_POST['flipkart_user_id'];
        $channel_id = $_POST['channel_id'];
        $start_date = $_POST['start_date'];
        $end_date = $_POST['end_date'];

        // Check if report exists for same user (uploader), date range
        // NOTE: allow same flipkart_user_id to be generated by different logged-in accounts
        $stmt = $pdo->prepare("SELECT * FROM flipkart_str_logs 
            WHERE flipkart_user_id = ? 
            AND channel_id = ?
            AND start_date = ?
            AND end_date = ?
            AND user_id = ?
            AND DATE(created_at) = CURRENT_DATE()
            LIMIT 1");
        $stmt->execute([$flipkart_user_id, $channel_id, $start_date, $end_date, $_SESSION['user_id']]);
        $existing_report = $stmt->fetch();

        if ($existing_report) {
            $message = "❌ Report already exists for today with same parameters: \n" .
                      "User ID: " . htmlspecialchars($flipkart_user_id) . "\n" .
                      "Date Range: " . $start_date . " to " . $end_date . "\n" .
                      "Previous Report ID: " . htmlspecialchars($existing_report['report_id']) . "\n" .
                      "Generated at: " . $existing_report['created_at'];
        } else {
            // STEP 1: Generate report API only (do NOT trigger upload here)
            $url1 = "https://cron.evanik.com/cronjobs/Flipkart/API/sales_tax.php?UserID=" . urlencode($flipkart_user_id) . "&channel_id=" . urlencode($channel_id) . "&StartDate=" . urlencode($start_date) . "&EndDate=" . urlencode($end_date);

        $ch1 = curl_init();
        curl_setopt($ch1, CURLOPT_URL, $url1);
        curl_setopt($ch1, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch1, CURLOPT_HTTPHEADER, [
            "User-Agent: Mozilla/5.0",
            "Accept: application/json"
        ]);
        $response1 = curl_exec($ch1);
        $curlErr = curl_error($ch1);
        curl_close($ch1);

        $response1 = trim($response1);
        
        // Extract only the report_id from the response
        if (preg_match('/"report_id":"(R-[^"]+)"/', $response1, $matches)) {
            $report_id = $matches[1];  // This will get just the R-XXXXX part
        } else {
            // If no match found in JSON, try to clean the response
            // Remove any HTML and get only R-XXXXX pattern
            if (preg_match('/(R-[A-Z0-9]+)/', $response1, $matches)) {
                $report_id = $matches[1];
            } else {
                $report_id = "";
            }
        }

        if ($report_id && $report_id !== "" && $report_id !== "0") {
            // Save Log with clean report_id only
            $stmt = $pdo->prepare("INSERT INTO flipkart_str_logs (user_id, flipkart_user_id, channel_id, report_id, start_date, end_date) VALUES (?, ?, ?, ?, ?, ?)");
            $stmt->execute([$_SESSION['user_id'], $flipkart_user_id, $channel_id, $report_id, $start_date, $end_date]);

            $message = "✅ Report generated successfully. Report ID: $report_id";
        } else {
            $err = $curlErr ? "; curl error: $curlErr" : '';
            $message = "❌ Failed to generate report. Flipkart API did not return valid report_id.$err";
        }
        }
    }
}
?>
<!DOCTYPE html>
<html>
<head>
    <title>Flipkart Cron Dashboard</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            background-color: #1a1a1a;
            color: #ffffff;
        }
        .container {
            background-color: #2d2d2d;
            border-radius: 10px;
            padding: 20px;
            margin-top: 20px;
            box-shadow: 0 0 20px rgba(0,0,0,0.3);
        }
        .card {
            background-color: #363636;
            border: none;
            box-shadow: 0 4px 8px rgba(0,0,0,0.2);
        }
        .card-body {
            color: #ffffff;
        }
        .table {
            color: #ffffff;
            background-color: #2d2d2d;
        }
        .table th {
            background-color: #363636;
            border-color: #404040;
        }
        .table td {
            border-color: #404040;
        }
        .btn-success {
            background-color: #2ea44f;
            border: none;
        }
        .btn-primary {
            background-color: #2188ff;
            border: none;
        }
        .alert-info {
            background-color: #363636;
            border-color: #404040;
            color: #ffffff;
        }
        .form-control {
            background-color: #363636;
            border-color: #404040;
            color: #ffffff;
        }
        .form-control:focus {
            background-color: #404040;
            border-color: #2188ff;
            color: #ffffff;
            box-shadow: 0 0 0 0.2rem rgba(33,136,255,0.25);
        }
        label {
            color: #cccccc;
        }
        .text-muted {
            color: #888888 !important;
        }
        .badge-primary {
            background-color: #2188ff;
        }
    </style>
    <script>
    // Clean, reliable polling and AJAX upload trigger
    const activePolling = {};

    function checkUploadStatus(reportId) {
        console.log('Checking status for:', reportId);
        const statusDiv = document.getElementById('status-' + reportId);
        const mainStatusDiv = document.querySelector(`tr[data-report-id="${reportId}"] .upload-status`);

        if (!statusDiv && !mainStatusDiv) {
            if (activePolling[reportId]) {
                clearInterval(activePolling[reportId]);
                delete activePolling[reportId];
            }
            return;
        }

        fetch('sales_tax_check_status.php?report_id=' + encodeURIComponent(reportId))
            .then(r => {
                if (!r.ok) throw new Error('Network response was not ok');
                return r.json();
            })
            .then(data => {
                console.log('Status response:', data);
                const status = (data && data.status) ? data.status : '';
                if (status === 'COMPLETED' || status === 'SUCCESS') {
                    if (statusDiv) {
                        statusDiv.innerHTML = '✅ Uploaded Successfully';
                        statusDiv.classList.remove('text-warning','text-danger');
                        statusDiv.classList.add('text-success');
                    }
                    if (mainStatusDiv) {
                        mainStatusDiv.innerHTML = '<span class="text-success">✅ Uploaded</span>';
                        if (data.records) mainStatusDiv.innerHTML += `<br><small>(${data.records} records)</small>`;
                    }
                    if (activePolling[reportId]) {
                        clearInterval(activePolling[reportId]);
                        delete activePolling[reportId];
                    }
                    // Update UI inline (do not reload the page)
                    try {
                        // disable the Run Upload button for this row
                        const runBtn = document.querySelector(`tr[data-report-id="${reportId}"] button`);
                        if (runBtn) {
                            runBtn.disabled = true;
                            runBtn.classList.add('disabled');
                        }
                        // ensure final status is shown (already set above)
                        if (mainStatusDiv && data && data.records) {
                            // already appended records above; nothing else needed
                        }
                    } catch (e) {
                        console.error('Error finalizing UI after completion', e);
                    }
                } else {
                    const statusText = '⏳ PROCESSING... (auto-refreshing)';
                    if (statusDiv) {
                        statusDiv.innerHTML = statusText;
                        statusDiv.classList.remove('text-success','text-danger');
                        statusDiv.classList.add('text-warning');
                    }
                    if (mainStatusDiv) mainStatusDiv.innerHTML = `<span class="text-warning">${statusText}</span>`;
                }
            })
            .catch(err => {
                console.error('Error checking status', err);
                if (statusDiv) {
                    statusDiv.innerHTML = '❌ Error checking status';
                    statusDiv.classList.remove('text-warning','text-success');
                    statusDiv.classList.add('text-danger');
                }
                if (mainStatusDiv) mainStatusDiv.innerHTML = `<span class="text-danger">Error</span>`;
            });
    }

    function startStatusCheck(reportId) {
        console.log('Starting status check for:', reportId);
        if (activePolling[reportId]) {
            clearInterval(activePolling[reportId]);
        }
        checkUploadStatus(reportId);
        activePolling[reportId] = setInterval(() => checkUploadStatus(reportId), 2000);

        // stop polling after 5 minutes
        setTimeout(() => {
            if (activePolling[reportId]) {
                clearInterval(activePolling[reportId]);
                delete activePolling[reportId];
                const statusDiv = document.getElementById('status-' + reportId);
                if (statusDiv) {
                    statusDiv.innerHTML = '⚠️ Status check timed out, please refresh page';
                    statusDiv.classList.remove('text-warning','text-success');
                    statusDiv.classList.add('text-danger');
                }
            }
        }, 5 * 60 * 1000);
    }

    function runUpload(logId, reportId) {
        console.log('Starting upload for:', reportId);
        const statusDiv = document.getElementById('status-' + reportId);
        const mainStatusDiv = document.querySelector(`tr[data-report-id="${reportId}"] .upload-status`);
        if (statusDiv) {
            statusDiv.innerHTML = '⏳ Uploading...';
            statusDiv.classList.remove('text-success','text-danger');
            statusDiv.classList.add('text-warning');
        }
        if (mainStatusDiv) mainStatusDiv.innerHTML = '<span class="text-warning">⏳ Uploading...</span>';

        startStatusCheck(reportId);

        fetch('sales_tax_upload_trigger.php?log_id=' + encodeURIComponent(logId) + '&ajax=1', {
            method: 'GET',
            headers: { 'Accept': 'application/json' }
        })
        .then(r => r.json().catch(() => ({})))
        .then(data => {
            if (!data || data.success !== true) {
                if (statusDiv) {
                    statusDiv.innerHTML = '❌ Upload trigger failed';
                    statusDiv.classList.remove('text-warning');
                    statusDiv.classList.add('text-danger');
                }
                console.error('Upload trigger failed', data);
            } else {
                if (statusDiv) statusDiv.innerHTML = '⏳ Processing...';
            }
        })
        .catch(err => {
            console.error('Upload trigger error', err);
            if (statusDiv) {
                statusDiv.innerHTML = '❌ Upload trigger error';
                statusDiv.classList.remove('text-warning');
                statusDiv.classList.add('text-danger');
            }
        });
    }
    </script>
</head>
<body>
<div class="container mt-4">
    <h3>Welcome, <?= htmlspecialchars($_SESSION['display_name']) ?> 
        <?php if ($is_admin == 1): ?>
            <span class="badge badge-primary">Admin</span>
        <?php endif; ?>
    </h3>
    <a href="logout.php" class="btn btn-danger btn-sm float-right">Logout</a>
    
    <?php if ($is_admin == 1): ?>
    <div class="row mt-3">
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Total Users</h5>
                    <?php 
                    $user_count = $pdo->query("SELECT COUNT(*) FROM flipkart_str_users WHERE is_admin = 0")->fetchColumn();
                    echo "<h3>$user_count</h3>";
                    ?>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Today's Reports</h5>
                    <?php 
                    $today_reports = $pdo->query("SELECT COUNT(*) FROM flipkart_str_logs WHERE DATE(created_at) = CURRENT_DATE()")->fetchColumn();
                    echo "<h3>$today_reports</h3>";
                    ?>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Pending Uploads</h5>
                    <?php 
                    $pending = $pdo->query("SELECT COUNT(*) FROM run_reports WHERE status = 'PENDING'")->fetchColumn();
                    echo "<h3>$pending</h3>";
                    ?>
                </div>
            </div>
        </div>
    </div>
    <?php endif; ?>
    <hr>

    <?php if ($message): ?>
        <div class="alert alert-info"><?= $message ?></div>
    <?php endif; ?>

    <form method="POST">
        <input type="hidden" name="action" value="generate">
        <div class="form-group">
            <label>Flipkart User ID</label>
            <input type="text" name="flipkart_user_id" class="form-control" required>
        </div>
        <div class="form-group">
            <label>Channel ID</label>
            <input type="text" name="channel_id" class="form-control" required value="2">
        </div>
        <div class="form-group">
            <label>Start Date</label>
            <input type="date" name="start_date" class="form-control" required>
        </div>
        <div class="form-group">
            <label>End Date</label>
            <input type="date" name="end_date" class="form-control" required>
        </div>
        <button type="submit" class="btn btn-success btn-block">Generate Report ID</button>
    </form>

    <hr>
    <h5>Recent Logs</h5>
    <table class="table table-bordered">
        <tr>
            <th>Report ID</th>
            <th>Flipkart User ID</th>
            <th>Channel</th>
            <th>Date Range</th>
            <th>Created At</th>
            <?php if ($is_admin == 1): ?>
            <th>Created By</th>
            <?php endif; ?>
            <th>Upload Status</th>
            <th>Actions</th>
        </tr>
        <?php
        // Use the already checked is_admin value
        if ($is_admin == 1) {
            // Admin sees all logs
            $logs = $pdo->query("
                SELECT l.*, u.username as uploader_name 
                FROM flipkart_str_logs l 
                LEFT JOIN flipkart_str_users u ON l.user_id = u.id 
                ORDER BY l.id DESC 
                LIMIT 10
            ")->fetchAll(PDO::FETCH_ASSOC);
        } else {
            // Normal users see only their logs
            $stmt = $pdo->prepare("
                SELECT * FROM flipkart_str_logs 
                WHERE user_id = ? 
                ORDER BY id DESC 
                LIMIT 10
            ");
            $stmt->execute([$_SESSION['user_id']]);
            $logs = $stmt->fetchAll(PDO::FETCH_ASSOC);
        }
        foreach ($logs as $log):
            // Get latest upload status from run_reports table
            $stmt = $pdo->prepare("SELECT status, upload_response FROM run_reports WHERE report_id = ? ORDER BY created_at DESC LIMIT 1");
            $stmt->execute([$log['report_id']]);
            $run_status = $stmt->fetch(PDO::FETCH_ASSOC);
        ?>
        <tr data-report-id="<?= htmlspecialchars($log['report_id']) ?>">
            <td><?= htmlspecialchars($log['report_id']) ?></td>
            <td><?= htmlspecialchars($log['flipkart_user_id']) ?></td>
            <td><?= htmlspecialchars($log['channel_id']) ?></td>
            <td><?= $log['start_date'] ?> → <?= $log['end_date'] ?></td>
            <td><?= $log['created_at'] ?></td>
            <?php if ($is_admin == 1): ?>
            <td><?= htmlspecialchars($log['uploader_name'] ?? 'Unknown') ?></td>
            <?php endif; ?>
            <td class="upload-status">
                <?php if ($run_status): ?>
                    <?php if ($run_status['status'] === 'COMPLETED' || $run_status['status'] === 'SUCCESS'): ?>
                        <span class="text-success">✅ Uploaded</span>
                        <?php if (preg_match('/Record Updated (\d+)/', $run_status['upload_response'], $matches)): ?>
                            <br><small>(<?= $matches[1] ?> records)</small>
                        <?php endif; ?>
                    <?php elseif ($run_status['status'] === 'PENDING' || $run_status['status'] === 'PROCESSING'): ?>
                        <span class="text-warning">⏳ Processing</span>
                    <?php endif; ?>
                <?php else: ?>
                    <span class="text-muted">Not uploaded</span>
                <?php endif; ?>
            </td>
            <td>
                <?php if (!empty($log['report_id']) && $log['report_id'] !== '0'): ?>
                    <div>
                        <button type="button" class="btn btn-primary btn-sm" onclick="runUpload(<?= $log['id'] ?>, '<?= htmlspecialchars($log['report_id']) ?>'); return false;">Run Upload</button>
                        <div id="status-<?= htmlspecialchars($log['report_id']) ?>" class="mt-1"></div>
                    </div>
                <?php else: ?>
                    <span class="text-muted">No report_id</span>
                <?php endif; ?>
            </td>
        </tr>


        <?php endforeach; ?>
    </table>
</div>
</body>
</html>
